### ISSUE TITLE
update docs for Custom Scrapers

### ISSUE THREAD

**Issue by wearpants** [opensyllabus/osp-scraper#11] opened 2017-01-30 22:17 UTC
Please add a section to README with a high-level overview of how to write a custom scraper. Stuff like:
1. work on a branch named `scraper/<site_name>`. Each branch should contain a single site.
2. save your new scraper in `syllascrape/spiders/<site_name>.py`
3. Inherit from class `CustomSpider` and implement methods `x(), y(), z()`

**Comment by jodizzle** [comment] 2017-05-02 07:41
Duplicate of #81.
Closing in favor of newer issue.

**Closed** 2017-05-02 07:41 UTC
